#!/bin/bash
NUMBER_OF_CLIENTS=$('grep -E "^" "/root/usertrojan" | cut -d ' ' -f 1')
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		echo ""
		echo "You have no existing clients!"
		exit 1
	fi

	clear
	echo ""
	echo " ==============================="
	echo "    No   User           Date"
        grep -E "^" "/root/usertrojan" | cut -d ' ' -f 1-2| nl -s ') '
echo " =========================="
echo ""
