#!/bin/bash
read -p "Masukkan Username yang ingin anda hapus: " username
grep -E "^$username" /root/usertrojan >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
username2="/$username/d";
sed -i $username2 /root/usertrojan
sed -i $username2 /usr/local/etc/trojan/config.json
sed -i '/^$/d' /root/usertrojan
sed -i '/^$/d' /usr/local/etc/trojan/config.json
clear
  echo ""
  echo " "
  echo "-----------------------------------------------"
  echo -e "Username ${blue}$username${NC} Sudah berhasil di ${red}HAPUS${NC}."
  echo -e "Akses Login untuk username ${blue}$username${NC} sudah dihapus"
  echo "-----------------------------------------------"
else
echo "Username tidak ditemukan di server anda"
    exit 1
fi
